# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-23 00:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blocks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='板块名称')),
                ('manager', models.CharField(max_length=100, verbose_name='管理员')),
                ('create_timestamp', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('last_update_timestamp', models.DateTimeField(auto_now=True, verbose_name='最近一次更新时间')),
            ],
            options={
                'verbose_name': '板块',
                'verbose_name_plural': '板块',
            },
        ),
    ]
