# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-23 00:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articles',
            options={'verbose_name': '文章', 'verbose_name_plural': '文章'},
        ),
    ]
