# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-27 06:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='content',
            field=models.CharField(max_length=20000, verbose_name='文章内容'),
        ),
    ]
